name: Issue Interaction with ChatGPT

on:
  push:
    branches:
      - main
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "hello world"
